import { initialMastery, reduceDeterministic } from "./mastery-models.js";

export function createQuestionSnapshot(question) { return { questionFingerprint: question.questionFingerprint || null, learningOutcomeId: question.learningOutcome?.id || null, skillIds: [], conceptIds: [], difficulty: question.metadata?.difficulty?.value ?? null, questionType: question.classification?.questionType || null, analysisVersion: null, taxonomyVersion: "manual-v1" }; }
export class StudentEventService {
  constructor({ db, questionRepository, curriculumRepository, clock = () => new Date().toISOString(), idFactory = () => crypto.randomUUID() }) { Object.assign(this, { db, questionRepository, curriculumRepository, clock, idFactory }); }
  async submitAttempt(input) { const question = await this.questionRepository.getQuestion(input.questionId); if (!question) throw new Error("Question not found."); if (!input.studentId?.trim()) throw new TypeError("studentId is required."); if (typeof input.isCorrect !== "boolean" || Number(input.timeSpentMs) < 0 || !Number.isFinite(Number(input.timeSpentMs))) throw new TypeError("Attempt outcome/time is invalid."); const snapshot = createQuestionSnapshot(question); if (snapshot.learningOutcomeId && !(await this.curriculumRepository.getById(snapshot.learningOutcomeId))) throw new Error("Question learning outcome is not canonical."); const event = { id: input.id || this.idFactory(), studentId: input.studentId.trim(), questionId: Number(question.id), sessionId: input.sessionId != null ? Number(input.sessionId) : null, sessionItemId: input.sessionItemId != null ? Number(input.sessionItemId) : null, solvingId: input.solvingId || null, questionSnapshot: snapshot, timestamp: input.timestamp || this.clock(), isCorrect: input.isCorrect, outcome: input.outcome || (input.isCorrect ? "correct" : "wrong"), timeSpentMs: Number(input.timeSpentMs), attemptNumber: Math.max(1, Number(input.attemptNumber) || 1), hintUsed: Boolean(input.hintUsed), solutionViewed: Boolean(input.solutionViewed), skipped: Boolean(input.skipped), learningOutcomeId: snapshot.learningOutcomeId, skillIds: snapshot.skillIds, conceptIds: snapshot.conceptIds, difficulty: snapshot.difficulty, questionType: snapshot.questionType, source: input.source || "practice", createdAt: this.clock() };
    return this.db.transaction("rw", this.db.attemptEvents, this.db.studentMastery, async () => { const existing = await this.db.attemptEvents.get(event.id); if (existing) return { event: existing, mastery: await this.getMastery(event.studentId, event.skillIds), duplicate: true }; await this.db.attemptEvents.add(event); const mastery = []; for (const skillId of event.skillIds) { const key = `${event.studentId}:${skillId}`, current = await this.db.studentMastery.get(key) || initialMastery(event.studentId, skillId, event.createdAt), next = reduceDeterministic(current, event); await this.db.studentMastery.put(next); mastery.push(next); } return { event, mastery, duplicate: false }; }); }
  async getMastery(studentId, skillIds = null) { const rows = skillIds ? await Promise.all(skillIds.map((skillId) => this.db.studentMastery.get(`${studentId}:${skillId}`))) : await this.db.studentMastery.where("studentId").equals(studentId).toArray(); return rows.filter(Boolean); }
  async rebuildStudentMastery(studentId) { const events = await this.db.attemptEvents.where("studentId").equals(studentId).toArray(); const bySkill = new Map(); for (const event of events) for (const skill of event.skillIds) { const list = bySkill.get(skill) || []; list.push(event); bySkill.set(skill, list); } await this.db.transaction("rw", this.db.studentMastery, async () => { await this.db.studentMastery.where("studentId").equals(studentId).delete(); for (const [skill, skillEvents] of bySkill) { let state = initialMastery(studentId, skill); for (const event of skillEvents.sort((a,b) => new Date(a.timestamp)-new Date(b.timestamp))) state = reduceDeterministic(state,event); await this.db.studentMastery.put(state); } }); return this.getMastery(studentId); }
}
