import { createQuestionSkeleton } from "../questions/question-model.js";
import { curriculumSubjectForApp, appSubjectForCurriculum } from "../curriculum/core/subject-mapping.js";
import { normalizeQuestionType } from "../questions/question-config.js";

export const IMPORT_BATCH_SIZE = 50;
export const FINGERPRINT_VERSION = 1;
const clean = (value) => typeof value === "string" ? value.replace(/\s+/g, " ").trim() : value;
const fields = Object.freeze({ questionText: ["questionText", "question", "text"], choices: ["choices"], answer: ["answer", "correctAnswer"], solution: ["solution"], subject: ["subject", "ders"], grade: ["grade", "sinif"], unit: ["unit", "unite"], topic: ["topic", "konu"], difficulty: ["difficulty"], source: ["source"], year: ["year"], questionType: ["questionType"], learningOutcomeId: ["learningOutcomeId"] });
const pick = (row, names) => names.map((key) => row[key]).find((value) => value !== undefined && value !== null);

export class ImportParser {
  parse(text, type) { if (type === "json") { const data = JSON.parse(text); if (!Array.isArray(data)) throw new Error("JSON root must be an array."); return data; } if (type === "csv") return this.csv(text); throw new Error("Only JSON and CSV are supported."); }
  csv(text) { const rows = []; let row = [], cell = "", quoted = false; for (let i = 0; i < text.length; i++) { const c = text[i]; if (c === '"') { if (quoted && text[i + 1] === '"') { cell += '"'; i++; } else quoted = !quoted; } else if (c === "," && !quoted) { row.push(cell); cell = ""; } else if ((c === "\n" || c === "\r") && !quoted) { if (c === "\r" && text[i + 1] === "\n") i++; row.push(cell); if (row.some((value) => value !== "")) rows.push(row); row = []; cell = ""; } else cell += c; } if (quoted) throw new Error("CSV quoted field is not closed."); row.push(cell); if (row.some((value) => value !== "")) rows.push(row); const [header, ...body] = rows; return body.map((values) => Object.fromEntries(header.map((name, index) => [name.trim(), values[index] ?? ""]))); }
}
export class ImportNormalizer {
  normalize(raw) { const choices = pick(raw, fields.choices); const parsedChoices = Array.isArray(choices) ? choices : typeof choices === "string" ? choices.split(/\s*\|\s*/) : []; const subject = clean(pick(raw, fields.subject)); const canonicalSubject = curriculumSubjectForApp(subject); return { questionText: clean(pick(raw, fields.questionText) || ""), choices: parsedChoices.map((choice, index) => ({ id: String.fromCharCode(65 + index), content: clean(typeof choice === "object" ? choice.content : choice) || "" })), answer: clean(pick(raw, fields.answer) || "")?.toUpperCase(), solution: clean(pick(raw, fields.solution) || "") || null, subject: canonicalSubject, grade: clean(String(pick(raw, fields.grade) ?? "")) || null, unit: clean(pick(raw, fields.unit) || "") || null, topic: clean(pick(raw, fields.topic) || "") || null, difficulty: clean(String(pick(raw, fields.difficulty) ?? "")) || null, source: clean(pick(raw, fields.source) || "") || null, year: pick(raw, fields.year) ?? null, questionType: normalizeQuestionType(pick(raw, fields.questionType)), learningOutcomeId: clean(pick(raw, fields.learningOutcomeId) || "") || null }; }
}
export class FingerprintService { async fingerprint(record) { const payload = JSON.stringify({ questionText: record.questionText.toLocaleLowerCase("tr-TR"), choices: record.choices.map((item) => item.content.toLocaleLowerCase("tr-TR")), answer: record.answer }); const bytes = new TextEncoder().encode(payload); const digest = await crypto.subtle.digest("SHA-256", bytes); return [...new Uint8Array(digest)].map((x) => x.toString(16).padStart(2, "0")).join(""); } }
export class ImportValidator {
  constructor(curriculumRepository) { this.curriculumRepository = curriculumRepository; }
  async validate(record) { const errors = []; if (!record.questionText) errors.push(["EMPTY_QUESTION", "questionText", "Soru metni boş olamaz."]); if (record.choices.length < 2 || record.choices.some((item) => !item.content)) errors.push(["INVALID_CHOICES", "choices", "En az iki dolu seçenek gerekir."]); if (!record.choices.some((item) => item.id === record.answer)) errors.push(["INVALID_ANSWER", "answer", "Cevap mevcut seçeneklerden biri olmalıdır."]); if (!record.subject || !appSubjectForCurriculum(record.subject)) errors.push(["INVALID_SUBJECT", "subject", "Ders canonical mapping içinde değil."]); if (record.grade && !/^(9|10|11|12)$/.test(record.grade)) errors.push(["INVALID_GRADE", "grade", "Sınıf 9-12 arasında olmalıdır."]); if (record.year && (!Number.isInteger(Number(record.year)) || Number(record.year) < 1900 || Number(record.year) > new Date().getFullYear() + 1)) errors.push(["INVALID_YEAR", "year", "Yıl geçerli değil."]); if (record.learningOutcomeId && !(await this.curriculumRepository.getById(record.learningOutcomeId))) errors.push(["INVALID_OUTCOME", "learningOutcomeId", "Kazanım bulunamadı."]); return { valid: errors.length === 0, errors }; }
}
export class DuplicateService {
  constructor(repository) { this.repository = repository; }
  async classify(fingerprint, record, seen) { if (seen.has(fingerprint) || await this.repository.hasFingerprint(fingerprint)) return "EXACT_DUPLICATE"; seen.add(fingerprint); return "UNIQUE"; }
}
export class ImportRepository {
  constructor(db) { this.db = db; }
  async hasFingerprint(fingerprint) { return Boolean(await this.db.questions.where("questionFingerprint").equals(fingerprint).first()); }
  async createImport(record) { await this.db.imports.add(record); return record; }
  async writeBatch(importId, questions, errors, progress) { return this.db.transaction("rw", this.db.questions, this.db.imports, this.db.importErrors, async () => { if (questions.length) { await this.db.questions.bulkAdd(questions, { allKeys: true }); } if (errors.length) await this.db.importErrors.bulkAdd(errors); await this.db.imports.update(importId, progress); }); }
  async updateImport(id, patch) { return this.db.imports.update(id, patch); }
}
export class ImportJobService {
  constructor({ parser = new ImportParser(), normalizer = new ImportNormalizer(), validator, fingerprint = new FingerprintService(), duplicates, repository, batchSize = IMPORT_BATCH_SIZE, idFactory = () => `imp_${crypto.randomUUID()}` }) { Object.assign(this, { parser, normalizer, validator, fingerprint, duplicates, repository, batchSize, idFactory }); }
  async preview({ text, fileName = "import", fileType }) { const raw = this.parser.parse(text, fileType); const seen = new Set(), rows = [], errors = []; for (let index = 0; index < raw.length; index++) { const record = this.normalizer.normalize(raw[index]); const validation = await this.validator.validate(record); if (!validation.valid) { errors.push(...validation.errors.map(([code, field, message]) => ({ rowNumber: index + 1, code, field, message }))); rows.push({ record, state: "INVALID" }); continue; } const fingerprint = await this.fingerprint.fingerprint(record), state = await this.duplicates.classify(fingerprint, record, seen); rows.push({ record, fingerprint, state }); } const counts = { totalRecords: raw.length, validRecords: rows.filter((r) => r.state === "UNIQUE").length, invalidRecords: rows.filter((r) => r.state === "INVALID").length, duplicateRecords: rows.filter((r) => r.state === "EXACT_DUPLICATE").length, nearDuplicateRecords: 0 }; return { fileName, fileType, rows, errors, ...counts }; }
  async start(preview, { signal, onProgress = () => {} } = {}) { const importId = this.idFactory(), importRecord = { id: importId, fileName: preview.fileName, fileType: preview.fileType, createdAt: new Date().toISOString(), status: "processing", importedRecords: 0, fingerprintVersion: FINGERPRINT_VERSION, ...Object.fromEntries(["totalRecords", "validRecords", "invalidRecords", "duplicateRecords"].map((key) => [key, preview[key]])) }; await this.repository.createImport(importRecord); const unique = preview.rows.filter((row) => row.state === "UNIQUE"); for (let start = 0; start < unique.length; start += this.batchSize) { if (signal?.aborted) { await this.repository.updateImport(importId, { status: "cancelled" }); return { importId, status: "cancelled" }; } const batch = unique.slice(start, start + this.batchSize); const questions = batch.map(({ record, fingerprint }) => { const subject = appSubjectForCurriculum(record.subject); const skeleton = createQuestionSkeleton({ text: record.questionText, choices: record.choices, answer: record.answer, solution: record.solution, subjectId: subject?.id, subjectName: subject?.name, grade: record.grade, unitId: record.unit, unitName: record.unit, topicId: record.topic, topicName: record.topic, year: Number(record.year) || null, sourceName: record.source, questionType: record.questionType, learningOutcome: record.learningOutcomeId ? { id: record.learningOutcomeId, source: "import" } : null, status: "draft" }); skeleton.questionFingerprint = fingerprint; skeleton.fingerprintVersion = FINGERPRINT_VERSION; skeleton.importId = importId; return skeleton; }); const errors = start === 0 ? preview.errors.map((error) => ({ ...error, importId })) : []; const imported = start + batch.length; await this.repository.writeBatch(importId, questions, errors, { importedRecords: imported }); onProgress({ stage: "persist", completed: imported, total: unique.length }); } await this.repository.updateImport(importId, { status: "completed" }); return { importId, status: "completed", importedRecords: unique.length }; }
}
