import { redundancy } from "../retrieval/engine.js";
import { RECOMMENDATION_CONFIG } from "./configuration.js";
const clamp=(value)=>Math.max(0,Math.min(1,value));
const average=(items, fallback=0)=>items.length?items.reduce((sum,item)=>sum+item,0)/items.length:fallback;
const candidateQuestion=(candidate)=>candidate.question || candidate;
const skillsOf=(candidate)=>[];
const difficultyOf=(candidate)=>candidateQuestion(candidate).metadata?.difficulty?.value;

export function scoreRecommendation(candidate, context, config = RECOMMENDATION_CONFIG) { const question=candidateQuestion(candidate), skills=skillsOf(candidate), masteryRows=skills.map((skill)=>context.masteryBySkill?.[skill]).filter(Boolean); const effectiveMasteries=skills.map((skill)=>{const state=context.masteryBySkill?.[skill];return state?state.confidence*state.mastery+(1-state.confidence)*config.priorMastery:config.priorMastery;}); const confidence=average(masteryRows.map((row)=>row.confidence),0); const masteryGap=average(effectiveMasteries.map((value)=>1-value),.5); const effectiveMastery=1-masteryGap, difficulty=difficultyOf(candidate); const normalizedDifficulty=Number.isFinite(difficulty)?clamp((difficulty-1)/4):.5, targetDifficulty=clamp(effectiveMastery+config.challengeOffset), difficultyFit=1-Math.abs(normalizedDifficulty-targetDifficulty); const retrieval=clamp(candidate.relevanceScore ?? candidate.finalScore ?? 0); const recentError=average(skills.map((skill)=>context.recentErrors?.[skill]||0),0); const exposure=context.exposureByQuestion?.[question.id]||0, exposurePenalty=clamp(exposure/config.maxExposureForPenalty), novelty=1-exposurePenalty; const expectedLearningGain=clamp(masteryGap*difficultyFit*retrieval*(.75+.25*confidence)); const f={retrieval,retrievalRelevance:retrieval,masteryGap,difficultyFit,expectedLearningGain,recentError,novelty,exposurePenalty,redundancyPenalty:0,masteryConfidence:confidence}; const w=config.weights; let score=w.relevance*f.retrieval+w.masteryGap*f.masteryGap+w.difficultyFit*f.difficultyFit+w.expectedLearningGain*f.expectedLearningGain+w.recentError*f.recentError+w.novelty*f.novelty-w.exposurePenalty*f.exposurePenalty; const reasons=[];if(f.masteryGap>.55)reasons.push("targets_weak_skill");if(f.difficultyFit>.7)reasons.push("appropriate_difficulty");if(f.recentError>.1)reasons.push("recent_error_reinforcement");if(f.novelty>.7)reasons.push("low_exposure");if(f.retrieval>.1)reasons.push("retrieval_relevance");return {candidate,question,skills,score:clamp(score),featureScores:f,reasons}; }
export function selectRecommended(ranked, limit, config = RECOMMENDATION_CONFIG) { const selected=[],remaining=ranked.map((row)=>({...row,redundancyPenalty:0}));while(remaining.length&&selected.length<limit){let bestIndex=0,best=-Infinity;remaining.forEach((row,index)=>{const adjusted=row.score-config.redundancyWeight*row.redundancyPenalty;if(adjusted>best){best=adjusted;bestIndex=index;}});const chosen=remaining.splice(bestIndex,1)[0];chosen.featureScores.redundancyPenalty=chosen.redundancyPenalty;chosen.score=clamp(chosen.score-config.redundancyWeight*chosen.redundancyPenalty);if(chosen.redundancyPenalty>.15)chosen.reasons.push("diversity_adjusted");selected.push(chosen);for(const row of remaining)row.redundancyPenalty=Math.max(row.redundancyPenalty,redundancy(row.question,chosen.question));}return selected; }
export class DeterministicRecommendationEngine { constructor({config=RECOMMENDATION_CONFIG}={}){this.config=config;} recommend({studentId,candidates=[],recommendationContext,limit=20}){if(!studentId?.trim())throw new TypeError("studentId is required.");if(!Array.isArray(candidates))throw new TypeError("candidates must be an array.");if(!Number.isInteger(Number(limit))||limit<1||limit>100)throw new TypeError("limit must be 1-100.");if(!candidates.length)return{recommendations:[],reason:"NO_CANDIDATES",diagnostics:{candidateCount:0}};const context=recommendationContext||{};const ranked=candidates.map((candidate)=>scoreRecommendation(candidate,context,this.config)).sort((a,b)=>b.score-a.score||Number(a.question.id)-Number(b.question.id));const recommendations=selectRecommended(ranked,Number(limit),this.config).map((row,index)=>({questionId:row.question.id,rank:index+1,score:row.score,reasons:row.reasons,featureScores:row.featureScores,scoreVersion:this.config.scoreVersion,candidate:row.candidate}));return{recommendations,reason:null,diagnostics:{candidateCount:candidates.length,stateVersion:context.stateVersion||null,scoreVersion:this.config.scoreVersion}};} }
